name: Java Inspector 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  intellij-inspections:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Run IntelliJ Inspections
      uses: gps/intellij-inspections@master
      with:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INSPECTIONS_FILE: /opt/idea/bin/inspectionProfile.xml
        IGNORE_FILE_PATTERNS: |
          [
            ".*src/generated.*",
            ".*basedb/src.*"
          ]
