name: Java Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
    - name: Run IntelliJ
      uses: mridang/action-idea@master
      with:
        target: .
        profile: ./.idea/inspectionProfiles/Project_Default.xml
        output: ./output
        verbosity: v2
        scope: Inspection
        plugins: 1347

    - name: Upload inspection results
      uses: actions/upload-artifact@v2
      with:
        name: inspection-results
        path: output


