name: OWASP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build project with Maven
      run: mvn clean install
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'checkin'
        path: '.'
        format: 'HTML'

    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ${{github.workspace}}/reports
