name: Safety CLI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 


jobs:
  Safety_CLI_SCAN:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: actions/checkout@main
      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
