name: Python Security Scan

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python 3.10  
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Corrected the version specification

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r .
