name: Snyk Security Scan

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Dependencies
        run: |
          npm install

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test for JS Vulnerabilties
        run: snyk test --all-projects

