name: Static Code Analysis Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Static-Code-Analysis-Checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
